-- AlterTable
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "cnic" TEXT;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "joiningDate" TIMESTAMP(3);
